export enum MainMessage {
  WEBSOCKET_CLOSE = 'WEBSOCKET_CLOSE',
  EMULATOR_DISCONNECT = 'EMULATOR_DISCONNECT',
  SET_SERVER = 'SET_SERVER',
  SET_PLAYERS = 'SET_PLAYERS',
  SET_PLAYER = 'SET_PLAYER',
  SET_PLAYER_ID = 'SET_PLAYER_ID',
  SERVER_FULL = 'SERVER_FULL',
  WRONG_VERSION = 'WRONG_VERSION',
  CHAT_GLOBAL = 'CHAT_GLOBAL',
  CHAT_COMMAND = 'CHAT_COMMAND',
  SET_CONNECTION_ERROR = 'SET_CONNECTION_ERROR',
  CONSOLE_INFO = 'CONSOLE_INFO'
}

export enum RendererMessage {
  CREATE_CONNECTION = 'CREATE_CONNECTION',
  DISCONNECT = 'DISCONNECT',
  CREATE_EMULATOR_CONNECTION = 'CREATE_EMULATOR_CONNECTION',
  DISCONNECT_EMULATOR = 'DISCONNECT_EMULATOR',
  CHANGE_CHARACTER = 'CHANGE_CHARACTER',
  CHAT_GLOBAL = 'CHAT_GLOBAL',
  CHAT_COMMAND = 'CHAT_COMMAND'
}
